### ISSUE TITLE
[6pt] Styling (Design)

### ISSUE THREAD

**Issue by Olivier-Kango** [DaveZag/meal-master-backend#13]
•	You should follow the layout of [the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). You should change only the titles, descriptions, and photos - in order to create a website about something other than motorcycles.

•	Make the app responsive, creating both mobile and desktop versions;
- [ ] Make the Login and Signup page Reponsive

**Comment by kkasaija** [comment]
Done
