### ISSUE TITLE
Kanban board for the final capstone project

### ISSUE THREAD

**Issue by Olivier-Kango** [DaveZag/meal-master-backend#17]
This is the [Link](https://github.com/users/DaveZag/projects/2) to our github project.

We are 5 people:
- @Elijahdre 
- @Kaweesi-Matia 
- @DaveZag 
- @Kasaija-Kenneth 
- @Olivier-Kango 

### Screen short of our board
<img width="960" alt="screen" src="https://user-images.githubusercontent.com/108806646/223073503-281902af-2be4-44a1-840c-394ca01a7447.png">

**Comment by Meltrust** [comment]
Hi @Olivier-Kango,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)


Congratulations! 🎉 

### To highlight

- All tasks have been assigned, pointed, and have descriptions ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kkasaija** [comment]
Completed
